site_name: Recipes Collection
site_description: A collection of recipes and cooking guides
repo_url: https://github.com/TerryHowe/recipes
site_author: TerryHowe

theme: 
  name: readthedocs

edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
