site_name: Recipes Collection
site_description: A collection of recipes and cooking guides
repo_url: https://github.com/TerryHowe/recipes
site_author: TerryHowe

theme: 
  name: mkdocs

plugins:
  - awesome-pages
  - gen-files:
      scripts:
        - gen_nav.py
  - literate-nav

nav:
  - Home: index.md
  - Recipes:
    - Getting Started: recipes/getting-started.md
    - Breakfast Sausage: recipes/breakfast-sausage.md
    - Italian Sausage: recipes/italian-sausage.md
    - Chocolate Chip Cookies: recipes/chocolate-chip-cookies.md
    - Peach Jam: recipes/peach-jam.md
  - About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
